#!/bin/bash

#SBATCH --job-name=nnunet_training  
#SBATCH --chdir=/work/phalempi         # modify with your paths
#SBATCH --output=/work/%u/%x-%A-%a.log # give name and filepath for the .log file (console output)
#SBATCH --time=1080                 # modify with your time limit
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=7
#SBATCH --mem-per-cpu=60G
#SBATCH --mail-type=BEGIN,END       # modify with your mail preferences
#SBATCH -G nvidia-a100:1            # modify with your GPU preferences

##  activating  the virtual environment
source /home/phalempi/MPvenv/bin/activate # modify with your paths

## declaring the environment variable
export nnUNet_preprocessed="/data/bosys-nnunet/nnUNet_preprocessed" # modify with your path
export nnUNet_results="/work/phalempi/nnUNet_results" # modify with your path
export NNUNET_EARLY_STOP_ENABLED="1"
export NNUNET_EARLY_STOP_PATIENCE="20"
export NNUNET_EARLY_STOP_MIN_DELTA="0.001"

## Run training with nnUNet native command
nnUNetv2_train 304 3d_fullres $SLURM_ARRAY_TASK_ID -tr nnUNetTrainer_betterIgnoreSampling_earlyStopValLoss